extends Node

class Recipe:
	var ingredients: Array
	var result: String
	
	func _init(p_ingredients: Array, p_result: String):
		ingredients = p_ingredients
		result = p_result

@onready var current_node : String = ""
var playerName : String = "Косипоша"
@export var currentDeck : Dictionary
@export var cardsPath : Dictionary
@export var mix_recipes : Dictionary
@export var heat_recipes : Dictionary
@export var slice_recipes : Dictionary

func _ready() -> void:
	currentDeck = {
		"apple" : 3,
		"cucumber" : 4,
		"dusa" : 2,
		"mushroom" : 1
	}
	
	cardsPath = {
		"apple" : "res://scenes/cards/apple/apple.tscn",
		"apple_c" : "res://scenes/cards/apple/apple_c.tscn",
		"apple_f" : "res://scenes/cards/apple/apple_f.tscn",
		"apple_fc" : "res://scenes/cards/apple/apple_fc.tscn",
		"cucumber" : "res://scenes/cards/cucumber/cucumber.tscn",
		"cucumber_c" : "res://scenes/cards/cucumber/cucumber_c.tscn",
		"cucumber_f" : "res://scenes/cards/cucumber/cucumber_f.tscn",
		"cucumber_fc" : "res://scenes/cards/cucumber/cucumber_fc.tscn",
		"dusa" : "res://scenes/cards/dusa/dusa.tscn",
		"dusa_c" : "res://scenes/cards/dusa/dusa_c.tscn",
		"dusa_f" : "res://scenes/cards/dusa/dusa_f.tscn",
		"dusa_fc" : "res://scenes/cards/dusa/dusa_fc.tscn",
		"mushroom" : "res://scenes/cards/mushroom/mushroom.tscn",
		"mushroom_c" : "res://scenes/cards/mushroom/mushroom_c.tscn",
		"mushroom_f" : "res://scenes/cards/mushroom/mushroom_f.tscn",
		"mushroom_fc" : "res://scenes/cards/mushroom/mushroom_fc.tscn",
		"ziga" : "res://scenes/cards/ziga/ziga.tscn",
		"ziga_c" : "res://scenes/cards/ziga/ziga_c.tscn",
		"ziga_f" : "res://scenes/cards/ziga/ziga_f.tscn",
		"ziga_fc" : "res://scenes/cards/ziga/ziga_fc.tscn",
		"luna" : "res://scenes/cards/luna/luna.tscn",
		"luna_c" : "res://scenes/cards/luna/luna_c.tscn",
		"luna_f" : "res://scenes/cards/luna/luna_f.tscn",
		"luna_fc" : "res://scenes/cards/luna/luna_fc.tscn",
		"mix2" : "res://scenes/cards/mix2.tscn",
		"mix3" : "res://scenes/cards/mix3.tscn",
	}

	mix_recipes = {
	"mix2_apple_cucumber": Recipe.new(["apple", "cucumber"], "mix2"),
	"mix2_apple_cucumber_c": Recipe.new(["apple", "cucumber_c"], "mix2"),
	"mix2_apple_cucumber_f": Recipe.new(["apple", "cucumber_f"], "mix2"),
	"mix2_apple_cucumber_fc": Recipe.new(["apple", "cucumber_fc"], "mix2"),
	"mix2_apple_dusa": Recipe.new(["apple", "dusa"], "mix2"),
	"mix2_apple_dusa_c": Recipe.new(["apple", "dusa_c"], "mix2"),
	"mix2_apple_dusa_f": Recipe.new(["apple", "dusa_f"], "mix2"),
	"mix2_apple_dusa_fc": Recipe.new(["apple", "dusa_fc"], "mix2"),
	"mix2_apple_mushroom": Recipe.new(["apple", "mushroom"], "mix2"),
	"mix2_apple_mushroom_c": Recipe.new(["apple", "mushroom_c"], "mix2"),
	"mix2_apple_mushroom_f": Recipe.new(["apple", "mushroom_f"], "mix2"),
	"mix2_apple_mushroom_fc": Recipe.new(["apple", "mushroom_fc"], "mix2"),
	"mix2_apple_ziga": Recipe.new(["apple", "ziga"], "mix2"),
	"mix2_apple_ziga_c": Recipe.new(["apple", "ziga_c"], "mix2"),
	"mix2_apple_ziga_f": Recipe.new(["apple", "ziga_f"], "mix2"),
	"mix2_apple_ziga_fc": Recipe.new(["apple", "ziga_fc"], "mix2"),
	"mix2_apple_luna": Recipe.new(["apple", "luna"], "mix2"),
	"mix2_apple_luna_c": Recipe.new(["apple", "luna_c"], "mix2"),
	"mix2_apple_luna_f": Recipe.new(["apple", "luna_f"], "mix2"),
	"mix2_apple_luna_fc": Recipe.new(["apple", "luna_fc"], "mix2"),
	"mix2_apple_c_cucumber": Recipe.new(["apple_c", "cucumber"], "mix2"),
	"mix2_apple_c_cucumber_c": Recipe.new(["apple_c", "cucumber_c"], "mix2"),
	"mix2_apple_c_cucumber_f": Recipe.new(["apple_c", "cucumber_f"], "mix2"),
	"mix2_apple_c_cucumber_fc": Recipe.new(["apple_c", "cucumber_fc"], "mix2"),
	"mix2_apple_c_dusa": Recipe.new(["apple_c", "dusa"], "mix2"),
	"mix2_apple_c_dusa_c": Recipe.new(["apple_c", "dusa_c"], "mix2"),
	"mix2_apple_c_dusa_f": Recipe.new(["apple_c", "dusa_f"], "mix2"),
	"mix2_apple_c_dusa_fc": Recipe.new(["apple_c", "dusa_fc"], "mix2"),
	"mix2_apple_c_mushroom": Recipe.new(["apple_c", "mushroom"], "mix2"),
	"mix2_apple_c_mushroom_c": Recipe.new(["apple_c", "mushroom_c"], "mix2"),
	"mix2_apple_c_mushroom_f": Recipe.new(["apple_c", "mushroom_f"], "mix2"),
	"mix2_apple_c_mushroom_fc": Recipe.new(["apple_c", "mushroom_fc"], "mix2"),
	"mix2_apple_c_ziga": Recipe.new(["apple_c", "ziga"], "mix2"),
	"mix2_apple_c_ziga_c": Recipe.new(["apple_c", "ziga_c"], "mix2"),
	"mix2_apple_c_ziga_f": Recipe.new(["apple_c", "ziga_f"], "mix2"),
	"mix2_apple_c_ziga_fc": Recipe.new(["apple_c", "ziga_fc"], "mix2"),
	"mix2_apple_c_luna": Recipe.new(["apple_c", "luna"], "mix2"),
	"mix2_apple_c_luna_c": Recipe.new(["apple_c", "luna_c"], "mix2"),
	"mix2_apple_c_luna_f": Recipe.new(["apple_c", "luna_f"], "mix2"),
	"mix2_apple_c_luna_fc": Recipe.new(["apple_c", "luna_fc"], "mix2"),
	"mix2_apple_f_cucumber": Recipe.new(["apple_f", "cucumber"], "mix2"),
	"mix2_apple_f_cucumber_c": Recipe.new(["apple_f", "cucumber_c"], "mix2"),
	"mix2_apple_f_cucumber_f": Recipe.new(["apple_f", "cucumber_f"], "mix2"),
	"mix2_apple_f_cucumber_fc": Recipe.new(["apple_f", "cucumber_fc"], "mix2"),
	"mix2_apple_f_dusa": Recipe.new(["apple_f", "dusa"], "mix2"),
	"mix2_apple_f_dusa_c": Recipe.new(["apple_f", "dusa_c"], "mix2"),
	"mix2_apple_f_dusa_f": Recipe.new(["apple_f", "dusa_f"], "mix2"),
	"mix2_apple_f_dusa_fc": Recipe.new(["apple_f", "dusa_fc"], "mix2"),
	"mix2_apple_f_mushroom": Recipe.new(["apple_f", "mushroom"], "mix2"),
	"mix2_apple_f_mushroom_c": Recipe.new(["apple_f", "mushroom_c"], "mix2"),
	"mix2_apple_f_mushroom_f": Recipe.new(["apple_f", "mushroom_f"], "mix2"),
	"mix2_apple_f_mushroom_fc": Recipe.new(["apple_f", "mushroom_fc"], "mix2"),
	"mix2_apple_f_ziga": Recipe.new(["apple_f", "ziga"], "mix2"),
	"mix2_apple_f_ziga_c": Recipe.new(["apple_f", "ziga_c"], "mix2"),
	"mix2_apple_f_ziga_f": Recipe.new(["apple_f", "ziga_f"], "mix2"),
	"mix2_apple_f_ziga_fc": Recipe.new(["apple_f", "ziga_fc"], "mix2"),
	"mix2_apple_f_luna": Recipe.new(["apple_f", "luna"], "mix2"),
	"mix2_apple_f_luna_c": Recipe.new(["apple_f", "luna_c"], "mix2"),
	"mix2_apple_f_luna_f": Recipe.new(["apple_f", "luna_f"], "mix2"),
	"mix2_apple_f_luna_fc": Recipe.new(["apple_f", "luna_fc"], "mix2"),
	"mix2_apple_fc_cucumber": Recipe.new(["apple_fc", "cucumber"], "mix2"),
	"mix2_apple_fc_cucumber_c": Recipe.new(["apple_fc", "cucumber_c"], "mix2"),
	"mix2_apple_fc_cucumber_f": Recipe.new(["apple_fc", "cucumber_f"], "mix2"),
	"mix2_apple_fc_cucumber_fc": Recipe.new(["apple_fc", "cucumber_fc"], "mix2"),
	"mix2_apple_fc_dusa": Recipe.new(["apple_fc", "dusa"], "mix2"),
	"mix2_apple_fc_dusa_c": Recipe.new(["apple_fc", "dusa_c"], "mix2"),
	"mix2_apple_fc_dusa_f": Recipe.new(["apple_fc", "dusa_f"], "mix2"),
	"mix2_apple_fc_dusa_fc": Recipe.new(["apple_fc", "dusa_fc"], "mix2"),
	"mix2_apple_fc_mushroom": Recipe.new(["apple_fc", "mushroom"], "mix2"),
	"mix2_apple_fc_mushroom_c": Recipe.new(["apple_fc", "mushroom_c"], "mix2"),
	"mix2_apple_fc_mushroom_f": Recipe.new(["apple_fc", "mushroom_f"], "mix2"),
	"mix2_apple_fc_mushroom_fc": Recipe.new(["apple_fc", "mushroom_fc"], "mix2"),
	"mix2_apple_fc_ziga": Recipe.new(["apple_fc", "ziga"], "mix2"),
	"mix2_apple_fc_ziga_c": Recipe.new(["apple_fc", "ziga_c"], "mix2"),
	"mix2_apple_fc_ziga_f": Recipe.new(["apple_fc", "ziga_f"], "mix2"),
	"mix2_apple_fc_ziga_fc": Recipe.new(["apple_fc", "ziga_fc"], "mix2"),
	"mix2_apple_fc_luna": Recipe.new(["apple_fc", "luna"], "mix2"),
	"mix2_apple_fc_luna_c": Recipe.new(["apple_fc", "luna_c"], "mix2"),
	"mix2_apple_fc_luna_f": Recipe.new(["apple_fc", "luna_f"], "mix2"),
	"mix2_apple_fc_luna_fc": Recipe.new(["apple_fc", "luna_fc"], "mix2"),
	"mix2_cucumber_dusa": Recipe.new(["cucumber", "dusa"], "mix2"),
	"mix2_cucumber_dusa_c": Recipe.new(["cucumber", "dusa_c"], "mix2"),
	"mix2_cucumber_dusa_f": Recipe.new(["cucumber", "dusa_f"], "mix2"),
	"mix2_cucumber_dusa_fc": Recipe.new(["cucumber", "dusa_fc"], "mix2"),
	"mix2_cucumber_mushroom": Recipe.new(["cucumber", "mushroom"], "mix2"),
	"mix2_cucumber_mushroom_c": Recipe.new(["cucumber", "mushroom_c"], "mix2"),
	"mix2_cucumber_mushroom_f": Recipe.new(["cucumber", "mushroom_f"], "mix2"),
	"mix2_cucumber_mushroom_fc": Recipe.new(["cucumber", "mushroom_fc"], "mix2"),
	"mix2_cucumber_ziga": Recipe.new(["cucumber", "ziga"], "mix2"),
	"mix2_cucumber_ziga_c": Recipe.new(["cucumber", "ziga_c"], "mix2"),
	"mix2_cucumber_ziga_f": Recipe.new(["cucumber", "ziga_f"], "mix2"),
	"mix2_cucumber_ziga_fc": Recipe.new(["cucumber", "ziga_fc"], "mix2"),
	"mix2_cucumber_luna": Recipe.new(["cucumber", "luna"], "mix2"),
	"mix2_cucumber_luna_c": Recipe.new(["cucumber", "luna_c"], "mix2"),
	"mix2_cucumber_luna_f": Recipe.new(["cucumber", "luna_f"], "mix2"),
	"mix2_cucumber_luna_fc": Recipe.new(["cucumber", "luna_fc"], "mix2"),
	"mix2_cucumber_c_dusa": Recipe.new(["cucumber_c", "dusa"], "mix2"),
	"mix2_cucumber_c_dusa_c": Recipe.new(["cucumber_c", "dusa_c"], "mix2"),
	"mix2_cucumber_c_dusa_f": Recipe.new(["cucumber_c", "dusa_f"], "mix2"),
	"mix2_cucumber_c_dusa_fc": Recipe.new(["cucumber_c", "dusa_fc"], "mix2"),
	"mix2_cucumber_c_mushroom": Recipe.new(["cucumber_c", "mushroom"], "mix2"),
	"mix2_cucumber_c_mushroom_c": Recipe.new(["cucumber_c", "mushroom_c"], "mix2"),
	"mix2_cucumber_c_mushroom_f": Recipe.new(["cucumber_c", "mushroom_f"], "mix2"),
	"mix2_cucumber_c_mushroom_fc": Recipe.new(["cucumber_c", "mushroom_fc"], "mix2"),
	"mix2_cucumber_c_ziga": Recipe.new(["cucumber_c", "ziga"], "mix2"),
	"mix2_cucumber_c_ziga_c": Recipe.new(["cucumber_c", "ziga_c"], "mix2"),
	"mix2_cucumber_c_ziga_f": Recipe.new(["cucumber_c", "ziga_f"], "mix2"),
	"mix2_cucumber_c_ziga_fc": Recipe.new(["cucumber_c", "ziga_fc"], "mix2"),
	"mix2_cucumber_c_luna": Recipe.new(["cucumber_c", "luna"], "mix2"),
	"mix2_cucumber_c_luna_c": Recipe.new(["cucumber_c", "luna_c"], "mix2"),
	"mix2_cucumber_c_luna_f": Recipe.new(["cucumber_c", "luna_f"], "mix2"),
	"mix2_cucumber_c_luna_fc": Recipe.new(["cucumber_c", "luna_fc"], "mix2"),
	"mix2_cucumber_f_dusa": Recipe.new(["cucumber_f", "dusa"], "mix2"),
	"mix2_cucumber_f_dusa_c": Recipe.new(["cucumber_f", "dusa_c"], "mix2"),
	"mix2_cucumber_f_dusa_f": Recipe.new(["cucumber_f", "dusa_f"], "mix2"),
	"mix2_cucumber_f_dusa_fc": Recipe.new(["cucumber_f", "dusa_fc"], "mix2"),
	"mix2_cucumber_f_mushroom": Recipe.new(["cucumber_f", "mushroom"], "mix2"),
	"mix2_cucumber_f_mushroom_c": Recipe.new(["cucumber_f", "mushroom_c"], "mix2"),
	"mix2_cucumber_f_mushroom_f": Recipe.new(["cucumber_f", "mushroom_f"], "mix2"),
	"mix2_cucumber_f_mushroom_fc": Recipe.new(["cucumber_f", "mushroom_fc"], "mix2"),
	"mix2_cucumber_f_ziga": Recipe.new(["cucumber_f", "ziga"], "mix2"),
	"mix2_cucumber_f_ziga_c": Recipe.new(["cucumber_f", "ziga_c"], "mix2"),
	"mix2_cucumber_f_ziga_f": Recipe.new(["cucumber_f", "ziga_f"], "mix2"),
	"mix2_cucumber_f_ziga_fc": Recipe.new(["cucumber_f", "ziga_fc"], "mix2"),
	"mix2_cucumber_f_luna": Recipe.new(["cucumber_f", "luna"], "mix2"),
	"mix2_cucumber_f_luna_c": Recipe.new(["cucumber_f", "luna_c"], "mix2"),
	"mix2_cucumber_f_luna_f": Recipe.new(["cucumber_f", "luna_f"], "mix2"),
	"mix2_cucumber_f_luna_fc": Recipe.new(["cucumber_f", "luna_fc"], "mix2"),
	"mix2_cucumber_fc_dusa": Recipe.new(["cucumber_fc", "dusa"], "mix2"),
	"mix2_cucumber_fc_dusa_c": Recipe.new(["cucumber_fc", "dusa_c"], "mix2"),
	"mix2_cucumber_fc_dusa_f": Recipe.new(["cucumber_fc", "dusa_f"], "mix2"),
	"mix2_cucumber_fc_dusa_fc": Recipe.new(["cucumber_fc", "dusa_fc"], "mix2"),
	"mix2_cucumber_fc_mushroom": Recipe.new(["cucumber_fc", "mushroom"], "mix2"),
	"mix2_cucumber_fc_mushroom_c": Recipe.new(["cucumber_fc", "mushroom_c"], "mix2"),
	"mix2_cucumber_fc_mushroom_f": Recipe.new(["cucumber_fc", "mushroom_f"], "mix2"),
	"mix2_cucumber_fc_mushroom_fc": Recipe.new(["cucumber_fc", "mushroom_fc"], "mix2"),
	"mix2_cucumber_fc_ziga": Recipe.new(["cucumber_fc", "ziga"], "mix2"),
	"mix2_cucumber_fc_ziga_c": Recipe.new(["cucumber_fc", "ziga_c"], "mix2"),
	"mix2_cucumber_fc_ziga_f": Recipe.new(["cucumber_fc", "ziga_f"], "mix2"),
	"mix2_cucumber_fc_ziga_fc": Recipe.new(["cucumber_fc", "ziga_fc"], "mix2"),
	"mix2_cucumber_fc_luna": Recipe.new(["cucumber_fc", "luna"], "mix2"),
	"mix2_cucumber_fc_luna_c": Recipe.new(["cucumber_fc", "luna_c"], "mix2"),
	"mix2_cucumber_fc_luna_f": Recipe.new(["cucumber_fc", "luna_f"], "mix2"),
	"mix2_cucumber_fc_luna_fc": Recipe.new(["cucumber_fc", "luna_fc"], "mix2"),
	"mix2_dusa_mushroom": Recipe.new(["dusa", "mushroom"], "mix2"),
	"mix2_dusa_mushroom_c": Recipe.new(["dusa", "mushroom_c"], "mix2"),
	"mix2_dusa_mushroom_f": Recipe.new(["dusa", "mushroom_f"], "mix2"),
	"mix2_dusa_mushroom_fc": Recipe.new(["dusa", "mushroom_fc"], "mix2"),
	"mix2_dusa_ziga": Recipe.new(["dusa", "ziga"], "mix2"),
	"mix2_dusa_ziga_c": Recipe.new(["dusa", "ziga_c"], "mix2"),
	"mix2_dusa_ziga_f": Recipe.new(["dusa", "ziga_f"], "mix2"),
	"mix2_dusa_ziga_fc": Recipe.new(["dusa", "ziga_fc"], "mix2"),
	"mix2_dusa_luna": Recipe.new(["dusa", "luna"], "mix2"),
	"mix2_dusa_luna_c": Recipe.new(["dusa", "luna_c"], "mix2"),
	"mix2_dusa_luna_f": Recipe.new(["dusa", "luna_f"], "mix2"),
	"mix2_dusa_luna_fc": Recipe.new(["dusa", "luna_fc"], "mix2"),
	"mix2_dusa_c_mushroom": Recipe.new(["dusa_c", "mushroom"], "mix2"),
	"mix2_dusa_c_mushroom_c": Recipe.new(["dusa_c", "mushroom_c"], "mix2"),
	"mix2_dusa_c_mushroom_f": Recipe.new(["dusa_c", "mushroom_f"], "mix2"),
	"mix2_dusa_c_mushroom_fc": Recipe.new(["dusa_c", "mushroom_fc"], "mix2"),
	"mix2_dusa_c_ziga": Recipe.new(["dusa_c", "ziga"], "mix2"),
	"mix2_dusa_c_ziga_c": Recipe.new(["dusa_c", "ziga_c"], "mix2"),
	"mix2_dusa_c_ziga_f": Recipe.new(["dusa_c", "ziga_f"], "mix2"),
	"mix2_dusa_c_ziga_fc": Recipe.new(["dusa_c", "ziga_fc"], "mix2"),
	"mix2_dusa_c_luna": Recipe.new(["dusa_c", "luna"], "mix2"),
	"mix2_dusa_c_luna_c": Recipe.new(["dusa_c", "luna_c"], "mix2"),
	"mix2_dusa_c_luna_f": Recipe.new(["dusa_c", "luna_f"], "mix2"),
	"mix2_dusa_c_luna_fc": Recipe.new(["dusa_c", "luna_fc"], "mix2"),
	"mix2_dusa_f_mushroom": Recipe.new(["dusa_f", "mushroom"], "mix2"),
	"mix2_dusa_f_mushroom_c": Recipe.new(["dusa_f", "mushroom_c"], "mix2"),
	"mix2_dusa_f_mushroom_f": Recipe.new(["dusa_f", "mushroom_f"], "mix2"),
	"mix2_dusa_f_mushroom_fc": Recipe.new(["dusa_f", "mushroom_fc"], "mix2"),
	"mix2_dusa_f_ziga": Recipe.new(["dusa_f", "ziga"], "mix2"),
	"mix2_dusa_f_ziga_c": Recipe.new(["dusa_f", "ziga_c"], "mix2"),
	"mix2_dusa_f_ziga_f": Recipe.new(["dusa_f", "ziga_f"], "mix2"),
	"mix2_dusa_f_ziga_fc": Recipe.new(["dusa_f", "ziga_fc"], "mix2"),
	"mix2_dusa_f_luna": Recipe.new(["dusa_f", "luna"], "mix2"),
	"mix2_dusa_f_luna_c": Recipe.new(["dusa_f", "luna_c"], "mix2"),
	"mix2_dusa_f_luna_f": Recipe.new(["dusa_f", "luna_f"], "mix2"),
	"mix2_dusa_f_luna_fc": Recipe.new(["dusa_f", "luna_fc"], "mix2"),
	"mix2_dusa_fc_mushroom": Recipe.new(["dusa_fc", "mushroom"], "mix2"),
	"mix2_dusa_fc_mushroom_c": Recipe.new(["dusa_fc", "mushroom_c"], "mix2"),
	"mix2_dusa_fc_mushroom_f": Recipe.new(["dusa_fc", "mushroom_f"], "mix2"),
	"mix2_dusa_fc_mushroom_fc": Recipe.new(["dusa_fc", "mushroom_fc"], "mix2"),
	"mix2_dusa_fc_ziga": Recipe.new(["dusa_fc", "ziga"], "mix2"),
	"mix2_dusa_fc_ziga_c": Recipe.new(["dusa_fc", "ziga_c"], "mix2"),
	"mix2_dusa_fc_ziga_f": Recipe.new(["dusa_fc", "ziga_f"], "mix2"),
	"mix2_dusa_fc_ziga_fc": Recipe.new(["dusa_fc", "ziga_fc"], "mix2"),
	"mix2_dusa_fc_luna": Recipe.new(["dusa_fc", "luna"], "mix2"),
	"mix2_dusa_fc_luna_c": Recipe.new(["dusa_fc", "luna_c"], "mix2"),
	"mix2_dusa_fc_luna_f": Recipe.new(["dusa_fc", "luna_f"], "mix2"),
	"mix2_dusa_fc_luna_fc": Recipe.new(["dusa_fc", "luna_fc"], "mix2"),
	"mix2_mushroom_ziga": Recipe.new(["mushroom", "ziga"], "mix2"),
	"mix2_mushroom_ziga_c": Recipe.new(["mushroom", "ziga_c"], "mix2"),
	"mix2_mushroom_ziga_f": Recipe.new(["mushroom", "ziga_f"], "mix2"),
	"mix2_mushroom_ziga_fc": Recipe.new(["mushroom", "ziga_fc"], "mix2"),
	"mix2_mushroom_luna": Recipe.new(["mushroom", "luna"], "mix2"),
	"mix2_mushroom_luna_c": Recipe.new(["mushroom", "luna_c"], "mix2"),
	"mix2_mushroom_luna_f": Recipe.new(["mushroom", "luna_f"], "mix2"),
	"mix2_mushroom_luna_fc": Recipe.new(["mushroom", "luna_fc"], "mix2"),
	"mix2_mushroom_c_ziga": Recipe.new(["mushroom_c", "ziga"], "mix2"),
	"mix2_mushroom_c_ziga_c": Recipe.new(["mushroom_c", "ziga_c"], "mix2"),
	"mix2_mushroom_c_ziga_f": Recipe.new(["mushroom_c", "ziga_f"], "mix2"),
	"mix2_mushroom_c_ziga_fc": Recipe.new(["mushroom_c", "ziga_fc"], "mix2"),
	"mix2_mushroom_c_luna": Recipe.new(["mushroom_c", "luna"], "mix2"),
	"mix2_mushroom_c_luna_c": Recipe.new(["mushroom_c", "luna_c"], "mix2"),
	"mix2_mushroom_c_luna_f": Recipe.new(["mushroom_c", "luna_f"], "mix2"),
	"mix2_mushroom_c_luna_fc": Recipe.new(["mushroom_c", "luna_fc"], "mix2"),
	"mix2_mushroom_f_ziga": Recipe.new(["mushroom_f", "ziga"], "mix2"),
	"mix2_mushroom_f_ziga_c": Recipe.new(["mushroom_f", "ziga_c"], "mix2"),
	"mix2_mushroom_f_ziga_f": Recipe.new(["mushroom_f", "ziga_f"], "mix2"),
	"mix2_mushroom_f_ziga_fc": Recipe.new(["mushroom_f", "ziga_fc"], "mix2"),
	"mix2_mushroom_f_luna": Recipe.new(["mushroom_f", "luna"], "mix2"),
	"mix2_mushroom_f_luna_c": Recipe.new(["mushroom_f", "luna_c"], "mix2"),
	"mix2_mushroom_f_luna_f": Recipe.new(["mushroom_f", "luna_f"], "mix2"),
	"mix2_mushroom_f_luna_fc": Recipe.new(["mushroom_f", "luna_fc"], "mix2"),
	"mix2_mushroom_fc_ziga": Recipe.new(["mushroom_fc", "ziga"], "mix2"),
	"mix2_mushroom_fc_ziga_c": Recipe.new(["mushroom_fc", "ziga_c"], "mix2"),
	"mix2_mushroom_fc_ziga_f": Recipe.new(["mushroom_fc", "ziga_f"], "mix2"),
	"mix2_mushroom_fc_ziga_fc": Recipe.new(["mushroom_fc", "ziga_fc"], "mix2"),
	"mix2_mushroom_fc_luna": Recipe.new(["mushroom_fc", "luna"], "mix2"),
	"mix2_mushroom_fc_luna_c": Recipe.new(["mushroom_fc", "luna_c"], "mix2"),
	"mix2_mushroom_fc_luna_f": Recipe.new(["mushroom_fc", "luna_f"], "mix2"),
	"mix2_mushroom_fc_luna_fc": Recipe.new(["mushroom_fc", "luna_fc"], "mix2"),
	"mix2_ziga_luna": Recipe.new(["ziga", "luna"], "mix2"),
	"mix2_ziga_luna_c": Recipe.new(["ziga", "luna_c"], "mix2"),
	"mix2_ziga_luna_f": Recipe.new(["ziga", "luna_f"], "mix2"),
	"mix2_ziga_luna_fc": Recipe.new(["ziga", "luna_fc"], "mix2"),
	"mix2_ziga_c_luna": Recipe.new(["ziga_c", "luna"], "mix2"),
	"mix2_ziga_c_luna_c": Recipe.new(["ziga_c", "luna_c"], "mix2"),
	"mix2_ziga_c_luna_f": Recipe.new(["ziga_c", "luna_f"], "mix2"),
	"mix2_ziga_c_luna_fc": Recipe.new(["ziga_c", "luna_fc"], "mix2"),
	"mix2_ziga_f_luna": Recipe.new(["ziga_f", "luna"], "mix2"),
	"mix2_ziga_f_luna_c": Recipe.new(["ziga_f", "luna_c"], "mix2"),
	"mix2_ziga_f_luna_f": Recipe.new(["ziga_f", "luna_f"], "mix2"),
	"mix2_ziga_f_luna_fc": Recipe.new(["ziga_f", "luna_fc"], "mix2"),
	"mix2_ziga_fc_luna": Recipe.new(["ziga_fc", "luna"], "mix2"),
	"mix2_ziga_fc_luna_c": Recipe.new(["ziga_fc", "luna_c"], "mix2"),
	"mix2_ziga_fc_luna_f": Recipe.new(["ziga_fc", "luna_f"], "mix2"),
	"mix2_ziga_fc_luna_fc": Recipe.new(["ziga_fc", "luna_fc"], "mix2"),

	}

	heat_recipes = {
		"apple_f" : Recipe.new(["apple"], "apple_f"),
		"apple_fc" : Recipe.new(["apple_c"], "apple_fc"),
		"cucumber_f" : Recipe.new(["cucumber"], "cucumber_f"),
		"cucumber_fc" : Recipe.new(["cucumber_c"], "cucumber_fc"),
		"dusa_f" : Recipe.new(["dusa"], "dusa_f"),
		"dusa_fc" : Recipe.new(["dusa_c"], "dusa_fc"),
		"mushroom_f" : Recipe.new(["mushroom"], "mushroom_f"),
		"mushroom_fc" : Recipe.new(["mushroom_c"], "mushroom_fc"),
		"ziga_f" : Recipe.new(["ziga"], "ziga_f"),
		"ziga_fc" : Recipe.new(["ziga_c"], "ziga_fc"),
		"luna_f" : Recipe.new(["luna"], "luna_f"),
		"luna_fc" : Recipe.new(["luna_c"], "luna_fc")
	}

	slice_recipes = {
		"apple_c" : Recipe.new(["apple"], "apple_c"),
		"apple_fc" : Recipe.new(["apple_f"], "apple_fc"),
		"cucumber_c" : Recipe.new(["cucumber"], "cucumber_c"),
		"cucumber_fc" : Recipe.new(["cucumber_f"], "cucumber_fc"),
		"dusa_c" : Recipe.new(["dusa"], "dusa_c"),
		"dusa_fc" : Recipe.new(["dusa_f"], "dusa_fc"),
		"mushroom_c" : Recipe.new(["mushroom"], "mushroom_c"),
		"mushroom_fc" : Recipe.new(["mushroom_f"], "mushroom_fc"),
		"ziga_c" : Recipe.new(["ziga"], "ziga_c"),
		"ziga_fc" : Recipe.new(["ziga_f"], "ziga_fc"),
		"luna_c" : Recipe.new(["luna"], "luna_c"),
		"luna_fc" : Recipe.new(["luna_f"], "luna_fc")
	}

func check_recipe(ingredients: Array, recipe_dict: Dictionary) -> Recipe:
	ingredients.sort() # Sort to ensure consistent ordering
	for recipe_name in recipe_dict:
		var recipe = recipe_dict[recipe_name]
		var recipe_ingredients = recipe.ingredients.duplicate()
		recipe_ingredients.sort()
		if recipe_ingredients == ingredients:
			return recipe
	return null
